const Actions = {
  Founder_Detail: 'Founder_Detail',
  Founder_Detail_SUCCESS: 'Founder_Detail_SUCCESS',
  Founder_Detail_FAILURE: 'Founder_Detail_FAILURE',

  Refresh_Access_Token: 'Refresh_Access_Token',
  Refresh_Access_Token_SUCCESS: 'Refresh_Access_Token_SUCCESS',
  Refresh_Access_Token_FAILURE: 'Refresh_Access_Token_FAILURE',

   
  
    Change_Password: "CHANGE_PASSWORD",
    Change_Password_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
    Change_Password_FAILURE: "CHANGE_PASSWORD_FAILURE",

  REMOVE_EVALUATION_QUESTION_LOADING: "REMOVE_EVALUATION_QUESTION_LOADING",
  REMOVE_EVALUATION_QUESTION_SUCCESS: "REMOVE_EVALUATION_QUESTION_SUCCESS",
  REMOVE_EVALUATION_QUESTION_FAILURE: "REMOVE_EVALUATION_QUESTION_FAILURE",
  

  Resource_Detail: "RESOURCE_DETAIL",
  Resource_Detail_SUCCESS: "RESOURCE_DETAIL_SUCCESS",
  Resource_Detail_FAILURE: "RESOURCE_DETAIL_FAILURE",
  REQUEST_RESOURCE_LOADING : "REQUEST_RESOURCE_LOADING",
  REQUEST_RESOURCE_SUCCESS : "REQUEST_RESOURCE_SUCCESS",
  REQUEST_RESOURCE_FAILURE : "REQUEST_RESOURCE_FAILURE",


  FETCH_ALL_MENTORS_LOADING: 'FETCH_ALL_MENTORS_LOADING',
  FETCH_ALL_MENTORS_SUCCESS: 'FETCH_ALL_MENTORS_SUCCESS',
  FETCH_ALL_MENTORS_FAILURE: 'FETCH_ALL_MENTORS_FAILURE',
    
    REQUEST_OFFICE_SPACE_LOADING: 'REQUEST_OFFICE_SPACE_LOADING',
    REQUEST_OFFICE_SPACE_SUCCESS: 'REQUEST_OFFICE_SPACE_SUCCESS',
    REQUEST_OFFICE_SPACE_FAILURE: 'REQUEST_OFFICE_SPACE_FAILURE',
    
    REQUEST_MENTOR_SESSION_LOADING: 'REQUEST_MENTOR_SESSION_LOADING',
    REQUEST_MENTOR_SESSION_SUCCESS: 'REQUEST_MENTOR_SESSION_SUCCESS',
    REQUEST_MENTOR_SESSION_FAILURE: 'REQUEST_MENTOR_SESSION_FAILURE',

    FETCH_ALL_MENTORS_LOADING: 'FETCH_ALL_MENTORS_LOADING',
  FETCH_ALL_MENTORS_SUCCESS: 'FETCH_ALL_MENTORS_SUCCESS',
  FETCH_ALL_MENTORS_FAILURE: 'FETCH_ALL_MENTORS_FAILURE',
  FETCH_ALL_MENTORS_LOADING: 'FETCH_ALL_MENTORS_LOADING',
  FETCH_ALL_MENTORS_SUCCESS: 'FETCH_ALL_MENTORS_SUCCESS',
  FETCH_ALL_MENTORS_FAILURE: 'FETCH_ALL_MENTORS_FAILURE',
  
  REQUEST_MENTOR_LOADING: 'REQUEST_MENTOR_LOADING',
  REQUEST_MENTOR_SUCCESS: 'REQUEST_MENTOR_SUCCESS',
  REQUEST_MENTOR_FAILURE: 'REQUEST_MENTOR_FAILURE',

  REQUEST_OFFICE_SPACE_LOADING: 'REQUEST_OFFICE_SPACE_LOADING',
  REQUEST_OFFICE_SPACE_SUCCESS: 'REQUEST_OFFICE_SPACE_SUCCESS',
  REQUEST_OFFICE_SPACE_FAILURE: 'REQUEST_OFFICE_SPACE_FAILURE',

  FETCH_ALL_REQUESTS_LOADING: "FETCH_ALL_REQUESTS_LOADING",
  FETCH_ALL_REQUESTS_SUCCESS: "FETCH_ALL_REQUESTS_SUCCESS",
  FETCH_ALL_REQUESTS_FAILURE: "FETCH_ALL_REQUESTS_FAILURE",

  FETCH_ALL_MENTORSHIP_REQUESTS_LOADING: 'FETCH_ALL_MENTORSHIP_REQUESTS_LOADING',
  FETCH_ALL_MENTORSHIP_REQUESTS_SUCCESS: 'FETCH_ALL_MENTORSHIP_REQUESTS_SUCCESS',
  FETCH_ALL_MENTORSHIP_REQUESTS_FAILURE: 'FETCH_ALL_MENTORSHIP_REQUESTS_FAILURE',
  
  FETCH_ALL_MENTORSHIP_REQUESTS_LOADING: 'FETCH_ALL_MENTORSHIP_REQUESTS_LOADING',
  FETCH_ALL_MENTORSHIP_REQUESTS_SUCCESS: 'FETCH_ALL_MENTORSHIP_REQUESTS_SUCCESS',
  FETCH_ALL_MENTORSHIP_REQUESTS_FAILURE: 'FETCH_ALL_MENTORSHIP_REQUESTS_FAILURE',

  FETCH_ALL_MENTORSHIP_REQUESTS_LOADING: 'FETCH_ALL_MENTORSHIP_REQUESTS_LOADING',
  FETCH_ALL_MENTORSHIP_REQUESTS_SUCCESS: 'FETCH_ALL_MENTORSHIP_REQUESTS_SUCCESS',
  FETCH_ALL_MENTORSHIP_REQUESTS_FAILURE: 'FETCH_ALL_MENTORSHIP_REQUESTS_FAILURE',
  
  UPLOAD_DOC_REQUEST: "UPLOAD_DOC_REQUEST",
  UPLOAD_DOC_SUCCESS: "UPLOAD_DOC_SUCCESS",
  UPLOAD_DOC_FAILURE: "UPLOAD_DOC_FAILURE",

  FETCH_REQUESTED_DOCS_REQUEST: "FETCH_REQUESTED_DOCS_REQUEST",
  FETCH_REQUESTED_DOCS_SUCCESS: "FETCH_REQUESTED_DOCS_SUCCESS",
  FETCH_REQUESTED_DOCS_FAILURE: "FETCH_REQUESTED_DOCS_FAILURE",

};

module.exports = Actions;
