const Actions = {
  Admin_Detail: 'Admin_Detail',
  Admin_Detail_SUCCESS: 'Admin_Detail_SUCCESS',
  Admin_Detail_FAILURE: 'Admin_Detail_FAILURE',

  Refresh_Access_Token: 'Refresh_Access_Token',
  Refresh_Access_Token_SUCCESS: 'Refresh_Access_Token_SUCCESS',
  Refresh_Access_Token_FAILURE: 'Refresh_Access_Token_FAILURE',

    Edit_Admin_Detail: "EDIT_ADMIN_DETAIL",
    Edit_Admin_Detail_SUCCESS: "EDIT_ADMIN_DETAIL_SUCCESS",
    Edit_Admin_Detail_FAILURE: "EDIT_ADMIN_DETAIL_FAILURE",
  
    Change_Password: "CHANGE_PASSWORD",
    Change_Password_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
    Change_Password_FAILURE: "CHANGE_PASSWORD_FAILURE",

  REMOVE_EVALUATION_QUESTION_LOADING: "REMOVE_EVALUATION_QUESTION_LOADING",
  REMOVE_EVALUATION_QUESTION_SUCCESS: "REMOVE_EVALUATION_QUESTION_SUCCESS",
  REMOVE_EVALUATION_QUESTION_FAILURE: "REMOVE_EVALUATION_QUESTION_FAILURE",
  

  Resource_Detail: "RESOURCE_DETAIL",
  Resource_Detail_SUCCESS: "RESOURCE_DETAIL_SUCCESS",
  Resource_Detail_FAILURE: "RESOURCE_DETAIL_FAILURE",
  REQUEST_RESOURCE_LOADING : "REQUEST_RESOURCE_LOADING",
  REQUEST_RESOURCE_SUCCESS : "REQUEST_RESOURCE_SUCCESS",
  REQUEST_RESOURCE_FAILURE : "REQUEST_RESOURCE_FAILURE",

  

};

module.exports = Actions;
