const Actions = {
  Admin_Detail: 'Admin_Detail',
  Admin_Detail_SUCCESS: 'Admin_Detail_SUCCESS',
  Admin_Detail_FAILURE: 'Admin_Detail_FAILURE',

  //refresh acess token

  Refresh_Access_Token: 'Refresh_Access_Token',
  Refresh_Access_Token_SUCCESS: 'Refresh_Access_Token_SUCCESS',
  Refresh_Access_Token_FAILURE: 'Refresh_Access_Token_FAILURE',

  //universal loader
  Increment_Universal_Loader: 'Increment_Universal_Loader',
  Decrement_Universal_Loader: 'Decrement_Universal_Loader',
  //screening question
  FetchALl_Screening_Question: 'FetchALl_Screening_Question',
  FetchALl_Screening_Question_SUCCESS: 'FetchALl_Screening_Question_SUCCESS',
  FetchALl_Screening_Question_FAILURE: 'FetchALl_Screening_Question_FAILURE',

  //create sceme
  Create_Scheme: 'Create_Scheme',
  Create_Scheme_SUCCESS: 'Create_Scheme_SUCCESS',
  Create_Scheme_FAILURE: 'Create_Scheme_FAILURE',

  //fetch schemes
  Fetch_Schemes: 'Fetch_Schemes',
  Fetch_Schemes_SUCCESS: 'Fetch_Schemes_SUCCESS',
  Fetch_Schemes_FAILURE: 'Fetch_Schemes_FAILURE',

  //fectch program
  Fetch_Program: 'Fetch_Program',
  Fetch_Program_SUCCESS: 'Fetch_Program_SUCCESS',
  Fetch_Program_FAILURE: 'Fetch_Program_FAILURE',

  // FETCH ALL MANAGERS AVAILABLE
  FETCH_ALL_MANAGER_LOADING: 'FETCH_ALL_MANAGER_LOADING',
  FETCH_ALL_MANAGER_SUCCESS: 'FETCH_ALL_MANAGER_SUCCESS',
  FETCH_ALL_MANAGER_FAILURE: 'FETCH_ALL_MANAGER_FAILURE',

  //assign manager
  ASSIGN_MANAGER_LOADING: 'ASSIGN_MANAGER_LOADING',
  ASSIGN_MANAGER_SUCCESS: 'ASSIGN_MANAGER_SUCCESS',
  ASSIGN_MANAGER_FAILURE: 'ASSIGN_MANAGER_FAILURE',

  //remove manager
  REMOVE_MANAGER_LOADING: 'REMOVE_MANAGER_LOADING',
  REMOVE_MANAGER_SUCCESS: 'REMOVE_MANAGER_SUCCESS',
  REMOVE_MANAGER_FAILURE: 'REMOVE_MANAGER_FAILURE',

  //GET MANAGER DETAILS
  GET_MANAGER_DETAILS_LOADING: 'GET_MANAGER_DETAILS_LOADING',
  GET_MANAGER_DETAILS_SUCCESS: 'GET_MANAGER_DETAILS_SUCCESS',
  GET_MANAGER_DETAILS_FAILURE: 'GET_MANAGER_DETAILS_FAILURE',

  //edit manager
  EDIT_MANAGER_DETAILS_LOADING: 'EDIT_MANAGER_DETAILS_LOADING',
  EDIT_MANAGER_DETAILS_SUCCESS: 'EDIT_MANAGER_DETAILS_SUCCESS',
  EDIT_MANAGER_DETAILS_FAILURE: 'EDIT_MANAGER_DETAILS_FAILURE',

  //add manager
  ADD_MANAGER_LOADING: 'ADD_MANAGER_LOADING',
  ADD_MANAGER_SUCCESS: 'ADD_MANAGER_SUCCESS',
  ADD_MANAGER_FAILURE: 'ADD_MANAGER_FAILURE',

  //delete manager
  DELETE_MANAGER_LOADING: 'DELETE_MANAGER_LOADING',
  DELETE_MANAGER_SUCCESS: 'DELETE_MANAGER_SUCCESS',
  DELETE_MANAGER_FAILURE: 'DELETE_MANAGER_FAILURE',

  //assignactvityuser
  ASSIGN_ACTIVITY_USER_LOADING: 'ASSIGN_ACTIVITY_USER_LOADING',
  ASSIGN_ACTIVITY_USER_SUCCESS: 'ASSIGN_ACTIVITY_USER_SUCCESS',
  ASSIGN_ACTIVITY_USER_FAILURE: 'ASSIGN_ACTIVITY_USER_FAILURE',

  //addactiveUser
  ADD_ACTIVITY_LOADING: 'ADD_ACTIVITY_LOADING',
  ADD_ACTIVITY_SUCCESS: 'ADD_ACTIVITY_SUCCESS',
  ADD_ACTIVITY_FAILURE: 'ADD_ACTIVITY_FAILURE',

  //fetchActivity
  FETCH_ACTIVITY_LOADING: 'FETCH_ACTIVITY_LOADING',
  FETCH_ACTIVITY_SUCCESS: 'FETCH_ACTIVITY_SUCCESS',
  FETCH_ACTIVITY_FAILURE: 'FETCH_ACTIVITY_FAILURE',

  //delteActivity
  DELETE_ACTIVITY_LOADING: 'DELETE_ACTIVITY_LOADING',
  DELETE_ACTIVITY_SUCCESS: 'DELETE_ACTIVITY_SUCCESS',
  DELETE_ACTIVITY_FAILURE: 'DELETE_ACTIVITY_FAILURE',

  //anaouncment
  ADD_ANNOUNCEMENT_LOADING: 'ADD_ANNOUNCEMENT_LOADING',
  ADD_ANNOUNCEMENT_SUCCESS: 'ADD_ANNOUNCEMENT_SUCCESS',
  ADD_ANNOUNCEMENT_FAILURE: 'ADD_ANNOUNCEMENT_FAILURE',
  GET_ANNOUNCEMENT_LOADING: 'GET_ANNOUNCEMENT_LOADING',
  GET_ANNOUNCEMENT_SUCCESS: 'GET_ANNOUNCEMENT_SUCCESS',
  GET_ANNOUNCEMENT_FAILURE: 'GET_ANNOUNCEMENT_FAILURE',
  DELETE_ANNOUNCEMENT_LOADING: 'DELETE_ANNOUNCEMENT_LOADING',
  DELETE_ANNOUNCEMENT_SUCCESS: 'DELETE_ANNOUNCEMENT_SUCCESS',
  DELETE_ANNOUNCEMENT_FAILURE: 'DELETE_ANNOUNCEMENT_FAILURE',

  //panel memeber
  FETCH_PANEL_MEMBER_LOADING: 'FETCH_PANEL_MEMBER_LOADING',
  FETCH_PANEL_MEMBER_SUCCESS: 'FETCH_PANEL_MEMBER_SUCCESS',
  FETCH_PANEL_MEMBER_FAILURE: 'FETCH_PANEL_MEMBER_FAILURE',

  ADD_PANEL_MEMBER_LOADING: 'ADD_PANEL_MEMBER_LOADING',
  ADD_PANEL_MEMBER_SUCCESS: 'ADD_PANEL_MEMBER_SUCCESS',
  ADD_PANEL_MEMBER_FAILURE: 'ADD_PANEL_MEMBER_FAILURE',

  CREATE_GUEST_LOADING : ' CREATE_GUEST_LOADING',
  CREATE_GUEST_SUCCESS :' CREATE_GUEST_SUCCESS',
  CREATE_GUEST_FAILURE :' CREATE_GUEST_FAILURE',

  REMOVE_PANEL_MEMBER_LOADING: 'REMOVE_PANEL_MEMBER_LOADING',
  REMOVE_PANEL_MEMBER_SUCCESS: 'REMOVE_PANEL_MEMBER_SUCCESS',
  REMOVE_PANEL_MEMBER_FAILURE: 'REMOVE_PANEL_MEMBER_FAILURE',

  CREATE_GUEST_LOADING: 'CREATE_GUEST_LOADING',
  CREATE_GUEST_SUCCESS: 'CREATE_GUEST_SUCCESS',
  CREATE_GUEST_FAILURE: 'CREATE_GUEST_FAILURE',
  
  FETCH_REGISTRATION_LOADING :'FETCH_REGISTRATION_LOADING',
  FETCH_REGISTRATION_SUCCESS :'FETCH_REGISTRATION_SUCCESS',
  FETCH_REGISTRATION_FAILURE :'FETCH_REGISTRATION_FAILURE',

  FETCH_STARTUP_DETAILS_LOADING:'FETCH_STARTUP_DETAILS_LOADING',
  FETCH_STARTUP_DETAILS_SUCCESS:'FETCH_STARTUP_DETAILS_SUCCESS',
  FETCH_STARTUP_DETAILS_FAILURE:'FETCH_STARTUP_DETAILS_FAILURE',

  REQUEST_CHANGE_REGISTRATION_LOADING :'REQUEST_CHANGE_REGISTRATION_LOADING',
  REQUEST_CHANGE_REGISTRATION_SUCCESS :'REQUEST_CHANGE_REGISTRATION_SUCCESS',
  REQUEST_CHANGE_REGISTRATION_FAILURE :'REQUEST_CHANGE_REGISTRATION_FAILURE',

    
  
    Edit_Admin_Detail: "EDIT_ADMIN_DETAIL",
    Edit_Admin_Detail_SUCCESS: "EDIT_ADMIN_DETAIL_SUCCESS",
    Edit_Admin_Detail_FAILURE: "EDIT_ADMIN_DETAIL_FAILURE",
  
    Change_Password: "CHANGE_PASSWORD",
    Change_Password_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
    Change_Password_FAILURE: "CHANGE_PASSWORD_FAILURE",

    FINAL_REVIEW_LOADING: 'FINAL_REVIEW_LOADING',
    FINAL_REVIEW_SUCCESS: 'FINAL_REVIEW_SUCCESS',
    FINAL_REVIEW_FAILURE: 'FINAL_REVIEW_FAILURE',
    
    // Delete Change
    DELETE_CHANGE_LOADING: 'DELETE_CHANGE_LOADING',
    DELETE_CHANGE_SUCCESS: 'DELETE_CHANGE_SUCCESS',
    DELETE_CHANGE_FAILURE: 'DELETE_CHANGE_FAILURE',

  DIRECT_REVIEW_REQUEST : 'DIRECT_REVIEW_REQUEST',
  DIRECT_REVIEW_SUCCESS : 'DIRECT_REVIEW_SUCCESS',
  DIRECT_REVIEW_FAILURE : 'DIRECT_REVIEW_FAILURE',

  //evaltion question
  FETCH_EVALUATION_QUESTION_LOADING:'FETCH_EVALUATION_QUESTION_LOADING',
  FETCH_EVALUATION_QUESTION_SUCCESS:'FETCH_EVALUATION_QUESTION_SUCCESS',
  FETCH_EVALUATION_QUESTION_FAILURE:'FETCH_EVALUATION_QUESTION_FAILURE',
  
  ADD_EVALUATION_QUESTION_LOADING: "ADD_EVALUATION_QUESTION_LOADING",
  ADD_EVALUATION_QUESTION_SUCCESS: "ADD_EVALUATION_QUESTION_SUCCESS",
  ADD_EVALUATION_QUESTION_FAILURE: "ADD_EVALUATION_QUESTION_FAILURE",

  REMOVE_EVALUATION_QUESTION_LOADING: "REMOVE_EVALUATION_QUESTION_LOADING",
  REMOVE_EVALUATION_QUESTION_SUCCESS: "REMOVE_EVALUATION_QUESTION_SUCCESS",
  REMOVE_EVALUATION_QUESTION_FAILURE: "REMOVE_EVALUATION_QUESTION_FAILURE",

  

};

module.exports = Actions;
