export const Admin_Detail = '/admin/getdetail';
export const Refresh_Access_Token = '/admin/refresh-accessToken';
export const FetchALl_Screening_Question =
  '/program/fetchschemequestions?filterStatus=0';
export const Create_Scheme = '/program/createscheme';
export const Fetch_Schemes = '/program/fetchScheme';
export const Fetch_All_Manager = '/admin/fetchmanagers';
export const ASSIGN_MANAGER = '/program/assignManagerToScheme';
export const REMOVE_MANAGER = '/program/removeManagerFromScheme';
export const GET_MANAGER_DETAILS = '/admin/fetchManagerDetails';
export const EDIT_MANAGER_DETAILS = '/manager/updateManager';
export const ADD_MANAGER = '/manager/signup';
export const DELETE_MANAGER = '/manager/deleteManager';
export const ASSIGN_ACTIVITY_USER = '/activity/serveUsers';
export const ADD_ACTIVITY = '/activity/addActivity';
export const FETCH_ACTIVITY = '/activity/fetchActivity';
export const DELETE_ACTIVITY = '/activity/deleteActivities';
export const GET_ANNOUNCEMENT = '/activity/fetchAnnouncements';
export const ADD_ANNOUNCEMENT = '/activity/addAnnouncements';
export const DELETE_ANNOUNCEMENT = '/activity/deleteAnnouncements';
export const FETCH_PANEL_MEMBER = '/evaluation/fetchPanelMembers';
export const ADD_PANEL_MEMBER = '/evaluation/addPanelMemberToScheme';
export const REMOVE_PANEL_MEMBER = '/evaluation/removePanelMemberFromScheme';
export const CREATE_GUEST = '/evaluation/addGuest';
export const FETCH_REGISTRATION = '/program/serveRegistrations'
export const FETCH_STARTUP_DETAILS = '/startupReview/fetchRegistrationDetails'
export const REQUEST_CHANGE_REGISTRATION ='/startupReview/requestChanges'
export const GET_ADMIN_DETAILS = '/admin/getdetail'
export const EDIT_ADMIN_DETAIL='/admin/updateDetails'
export const CHANGE_PASSWORD ='/admin/changepassword'
export const FINAL_REVIEW ='/startupReview//finalReview'
export const DELETE_CHANGES = '/startupReview/deleteRequestedChanges'
export const DIRECT_REVIEW ='/startupReview/directReview'
export const FETCH_EVALUATION_QUESTION = '/program/fetchEvaluationQuestions'
export const ADD_EVALUATION_QUESTION = '/program/addEvaluationQuestions'
export const REMOVE_EVALUATION_QUESTION = '/program/removeEvaluationQuestionFromScheme'
