export const Founder_Detail = '/founder/getdetail';
export const Refresh_Access_Token = '/founder/refresh-accessToken';
export const Founder_Resource = '/founder/requestResources'
export const FetchALl_Screening_Question =
  '/program/fetchschemequestions?filterStatus=0';
export const Get_Requests = '/startup/fetchAllRequests'
export const Create_Scheme = '/program/createscheme';
export const Fetch_Schemes = '/program/fetchScheme';
export const Fetch_All_Manager = '/admin/fetchmanagers';
export const ASSIGN_MANAGER = '/program/assignManagerToScheme';
export const REMOVE_MANAGER = '/program/removeManagerFromScheme';
export const GET_MANAGER_DETAILS = '/admin/fetchManagerDetails';
export const EDIT_MANAGER_DETAILS = '/manager/updateManager';
export const ADD_MANAGER = '/manager/signup';
export const DELETE_MANAGER = '/manager/deleteManager';
export const ASSIGN_ACTIVITY_USER = '/activity/serveUsers';
export const ADD_ACTIVITY = '/activity/addActivity';
export const FETCH_ACTIVITY = '/activity/fetchActivity';
export const DELETE_ACTIVITY = '/activity/deleteActivities';
export const GET_ANNOUNCEMENT = '/activity/fetchAnnouncements';
export const ADD_ANNOUNCEMENT = '/activity/addAnnouncements';
export const DELETE_ANNOUNCEMENT = '/activity/deleteAnnouncements';
export const FETCH_PANEL_MEMBER = '/evaluation/fetchPanelMembers';
export const ADD_PANEL_MEMBER = '/evaluation/addPanelMemberToScheme';
export const REMOVE_PANEL_MEMBER = '/evaluation/removePanelMemberFromScheme';
export const FETCH_STARTUP_DETAILS = '/startupReview/fetchRegistrationDetails'
export const REQUEST_CHANGE_REGISTRATION ='/startupReview/requestChanges'
export const GET_ADMIN_DETAILS = '/founder/getdetail'
export const CHANGE_PASSWORD ='/admin/changepassword'
export const FINAL_REVIEW ='/startupReview//finalReview'
export const DELETE_CHANGES = '/startupReview/deleteRequestedChanges'
export const DIRECT_REVIEW ='/startupReview/directReview'
export const FETCH_EVALUATION_QUESTION = '/program/fetchEvaluationQuestions'
export const Resource_Detail ='/startup/fetchAllResources'
export const GET_CHAT_USER = '/chat/serveChatUsers'
export const GET_CHAT_MESSAGES = '/chat/fetchMessages'
export const SEARCH_CHAT_USER='/chat/searchUsers'

